// Generated by tools/generate-contracts.py from the pinned native schemas.
#nullable enable
using System.Collections.Immutable;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Zeroshot.Native.Contracts;

[WireContract("ArtifactLineage")]
public sealed record ArtifactLineage : NativeContract
{
    [JsonPropertyName("attempt")]
    public required PositiveInteger Attempt { get; init; }
    [JsonPropertyName("generation")]
    public required Generation Generation { get; init; }
    [JsonPropertyName("runId")]
    public required RunId RunId { get; init; }
}

[WireContract("ArtifactProducer")]
public sealed record ArtifactProducer : NativeContract
{
    [JsonPropertyName("node")]
    public required NodeName Node { get; init; }
    [JsonPropertyName("worker")]
    public required WorkerRef Worker { get; init; }
}

[WireContract("ArtifactRef")]
public sealed record ArtifactRef : NativeContract
{
    [JsonPropertyName("artifactId")]
    public required ArtifactId ArtifactId { get; init; }
    [JsonPropertyName("byteLength")]
    public required ByteLength ByteLength { get; init; }
    [JsonPropertyName("lineage")]
    public required ArtifactLineage Lineage { get; init; }
    [JsonPropertyName("mediaType")]
    public required MediaType MediaType { get; init; }
    [JsonPropertyName("producer")]
    public required ArtifactProducer Producer { get; init; }
    [JsonPropertyName("redaction")]
    public required RedactionClass Redaction { get; init; }
    [JsonPropertyName("sha256")]
    public required Sha256Digest Sha256 { get; init; }
    [JsonPropertyName("typeId")]
    public required TypeId TypeId { get; init; }
}

[WireContract("ArtifactResultProfile")]
public sealed record ArtifactResultProfile : NativeContract
{
    [JsonPropertyName("allowedMediaTypes")]
    public required ImmutableArray<string> AllowedMediaTypes { get; init; }
    [JsonPropertyName("allowedTypeIds")]
    public required ImmutableArray<string> AllowedTypeIds { get; init; }
    [JsonPropertyName("minimumRedaction")]
    public required RedactionClass MinimumRedaction { get; init; }
}

[WireContract("AutonomyPolicy")]
public enum AutonomyPolicy
{
    [JsonStringEnumMemberName("strict")]
    Strict,
}

[WireContract("CapabilityPolicy")]
public sealed record CapabilityPolicy : NativeContract
{
    [JsonPropertyName("autonomy")]
    public required AutonomyPolicy Autonomy { get; init; }
    [JsonPropertyName("permissionPolicy")]
    public required PolicyRef PermissionPolicy { get; init; }
}

[WireContract("ChoiceBranch")]
public sealed record ChoiceBranch : NativeContract
{
    [JsonPropertyName("node")]
    public required GraphNode Node { get; init; }
    [JsonPropertyName("when")]
    public required Guard When { get; init; }
}

[WireContract("ClaudeProvider")]
public enum ClaudeProvider
{
    [JsonStringEnumMemberName("anthropic")]
    Anthropic,
    [JsonStringEnumMemberName("openrouter")]
    OpenRouter,
    [JsonStringEnumMemberName("gateway")]
    Gateway,
    [JsonStringEnumMemberName("bedrock")]
    Bedrock,
}

[WireContract("CodexProvider")]
public enum CodexProvider
{
    [JsonStringEnumMemberName("openai")]
    OpenAi,
    [JsonStringEnumMemberName("openrouter")]
    OpenRouter,
    [JsonStringEnumMemberName("gateway")]
    Gateway,
    [JsonStringEnumMemberName("bedrock")]
    Bedrock,
}

[WireContract("ControlSelector")]
public sealed record ControlSelector : NativeContract
{
    [JsonPropertyName("field")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<FieldName?> Field { get; init; }
    [JsonPropertyName("name")]
    public required NodeName Name { get; init; }
    [JsonPropertyName("source")]
    public required ControlSource Source { get; init; }
}

[WireContract("ControlSource")]
public enum ControlSource
{
    [JsonStringEnumMemberName("signal")]
    Signal,
    [JsonStringEnumMemberName("error")]
    Error,
    [JsonStringEnumMemberName("group")]
    Group,
}

[WireContract("CopilotProvider")]
public enum CopilotProvider
{
    [JsonStringEnumMemberName("github")]
    Github,
}

[WireContract("DataSelector")]
[JsonPolymorphic(TypeDiscriminatorPropertyName = "source")]
[JsonDerivedType(typeof(StateSelector), "state")]
[JsonDerivedType(typeof(ItemSelector), "item")]
public abstract record DataSelector : NativeContract
{
    private protected DataSelector() { }
}

[WireContract("DataSelector")]
public sealed record StateSelector : DataSelector
{
    [JsonPropertyName("path")]
    public required ImmutableArray<string> Path { get; init; }
}

[WireContract("DataSelector")]
public sealed record ItemSelector : DataSelector
{
    [JsonPropertyName("path")]
    public required ImmutableArray<string> Path { get; init; }
}

[WireContract("DiagnosticPathSegment")]
[JsonPolymorphic(TypeDiscriminatorPropertyName = "kind")]
[JsonDerivedType(typeof(FieldDiagnosticPathSegment), "field")]
[JsonDerivedType(typeof(IndexDiagnosticPathSegment), "index")]
[JsonDerivedType(typeof(NodeDiagnosticPathSegment), "node")]
public abstract record DiagnosticPathSegment : NativeContract
{
    private protected DiagnosticPathSegment() { }
}

[WireContract("DiagnosticPathSegment")]
public sealed record FieldDiagnosticPathSegment : DiagnosticPathSegment
{
    [JsonPropertyName("name")]
    public required FieldName Name { get; init; }
}

[WireContract("DiagnosticPathSegment")]
public sealed record IndexDiagnosticPathSegment : DiagnosticPathSegment
{
    [JsonPropertyName("index")]
    public required uint Index { get; init; }
}

[WireContract("DiagnosticPathSegment")]
public sealed record NodeDiagnosticPathSegment : DiagnosticPathSegment
{
    [JsonPropertyName("name")]
    public required NodeName Name { get; init; }
}

[WireContract("DiagnosticSeverity")]
public enum DiagnosticSeverity
{
    [JsonStringEnumMemberName("error")]
    Error,
    [JsonStringEnumMemberName("warning")]
    Warning,
    [JsonStringEnumMemberName("info")]
    Info,
}

[WireContract("GraphDiagnostic")]
public sealed record GraphDiagnostic : NativeContract
{
    [JsonPropertyName("code")]
    public required GraphDiagnosticCode Code { get; init; }
    [JsonPropertyName("message")]
    public required string Message { get; init; }
    [JsonPropertyName("path")]
    public required ImmutableArray<DiagnosticPathSegment> Path { get; init; }
    [JsonPropertyName("relatedNodes")]
    public required ImmutableArray<string> RelatedNodes { get; init; }
    [JsonPropertyName("severity")]
    public required DiagnosticSeverity Severity { get; init; }
}

[WireContract("GraphDiagnosticCode")]
public enum GraphDiagnosticCode
{
    [JsonStringEnumMemberName("schema_safety")]
    SchemaSafety,
    [JsonStringEnumMemberName("reachability")]
    Reachability,
    [JsonStringEnumMemberName("choice_exhaustiveness")]
    ChoiceExhaustiveness,
    [JsonStringEnumMemberName("loop_exit_satisfiability")]
    LoopExitSatisfiability,
    [JsonStringEnumMemberName("missing_bound")]
    MissingBound,
    [JsonStringEnumMemberName("write_conflict")]
    WriteConflict,
    [JsonStringEnumMemberName("ceiling_exceeded")]
    CeilingExceeded,
    [JsonStringEnumMemberName("cyclic_reference")]
    CyclicReference,
    [JsonStringEnumMemberName("undefined_read")]
    UndefinedRead,
    [JsonStringEnumMemberName("invalid_graph_shape")]
    InvalidGraphShape,
}

[WireContract("GraphNode")]
[JsonPolymorphic(TypeDiscriminatorPropertyName = "kind")]
[JsonDerivedType(typeof(StepNode), "step")]
[JsonDerivedType(typeof(VerifierNode), "verifier")]
[JsonDerivedType(typeof(SeqNode), "seq")]
[JsonDerivedType(typeof(ChoiceNode), "choice")]
[JsonDerivedType(typeof(ParNode), "par")]
[JsonDerivedType(typeof(LoopNode), "loop")]
[JsonDerivedType(typeof(MapNode), "map")]
[JsonDerivedType(typeof(SucceedNode), "succeed")]
[JsonDerivedType(typeof(FailNode), "fail")]
public abstract record GraphNode : NativeContract
{
    private protected GraphNode() { }
}

[WireContract("GraphNode")]
public sealed record StepNode : GraphNode
{
    [JsonPropertyName("attempts")]
    public required PositiveInteger Attempts { get; init; }
    [JsonPropertyName("input")]
    public required PayloadType Input { get; init; }
    [JsonPropertyName("inputBindings")]
    public required ImmutableArray<InputBinding> InputBindings { get; init; }
    [JsonPropertyName("instructions")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<NodeInstructions?> Instructions { get; init; }
    [JsonPropertyName("name")]
    public required NodeName Name { get; init; }
    [JsonPropertyName("output")]
    public required PayloadType Output { get; init; }
    [JsonPropertyName("timeoutMs")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<PositiveInteger?> TimeoutMs { get; init; }
    [JsonPropertyName("worker")]
    public required WorkerRef Worker { get; init; }
    [JsonPropertyName("writeBindings")]
    public required ImmutableArray<WriteBinding> WriteBindings { get; init; }
}

[WireContract("GraphNode")]
public sealed record VerifierNode : GraphNode
{
    [JsonPropertyName("attempts")]
    public required PositiveInteger Attempts { get; init; }
    [JsonPropertyName("diagnostic")]
    public required PayloadType Diagnostic { get; init; }
    [JsonPropertyName("input")]
    public required PayloadType Input { get; init; }
    [JsonPropertyName("inputBindings")]
    public required ImmutableArray<InputBinding> InputBindings { get; init; }
    [JsonPropertyName("instructions")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<NodeInstructions?> Instructions { get; init; }
    [JsonPropertyName("name")]
    public required NodeName Name { get; init; }
    [JsonPropertyName("output")]
    public required PayloadType Output { get; init; }
    [JsonPropertyName("signals")]
    public required ImmutableDictionary<string, ImmutableArray<string>> Signals { get; init; }
    [JsonPropertyName("timeoutMs")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<PositiveInteger?> TimeoutMs { get; init; }
    [JsonPropertyName("worker")]
    public required WorkerRef Worker { get; init; }
    [JsonPropertyName("writeBindings")]
    public required ImmutableArray<WriteBinding> WriteBindings { get; init; }
}

[WireContract("GraphNode")]
public sealed record SeqNode : GraphNode
{
    [JsonPropertyName("children")]
    public required ImmutableArray<GraphNode> Children { get; init; }
    [JsonPropertyName("name")]
    public required NodeName Name { get; init; }
    [JsonPropertyName("promotedStatePaths")]
    public required ImmutableArray<ImmutableArray<string>> PromotedStatePaths { get; init; }
    [JsonPropertyName("state")]
    public required PayloadType State { get; init; }
}

[WireContract("GraphNode")]
public sealed record ChoiceNode : GraphNode
{
    [JsonPropertyName("branches")]
    public required ImmutableArray<ChoiceBranch> Branches { get; init; }
    [JsonPropertyName("name")]
    public required NodeName Name { get; init; }
    [JsonPropertyName("otherwise")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<GraphNode?> Otherwise { get; init; }
    [JsonPropertyName("promotedStatePaths")]
    public required ImmutableArray<ImmutableArray<string>> PromotedStatePaths { get; init; }
    [JsonPropertyName("state")]
    public required PayloadType State { get; init; }
}

[WireContract("GraphNode")]
public sealed record ParNode : GraphNode
{
    [JsonPropertyName("branches")]
    public required ImmutableArray<GraphNode> Branches { get; init; }
    [JsonPropertyName("join")]
    public required Join Join { get; init; }
    [JsonPropertyName("name")]
    public required NodeName Name { get; init; }
    [JsonPropertyName("promotedStatePaths")]
    public required ImmutableArray<ImmutableArray<string>> PromotedStatePaths { get; init; }
    [JsonPropertyName("state")]
    public required PayloadType State { get; init; }
}

[WireContract("GraphNode")]
public sealed record LoopNode : GraphNode
{
    [JsonPropertyName("body")]
    public required GraphNode Body { get; init; }
    [JsonPropertyName("maxIterations")]
    public required PositiveInteger MaxIterations { get; init; }
    [JsonPropertyName("name")]
    public required NodeName Name { get; init; }
    [JsonPropertyName("promotedStatePaths")]
    public required ImmutableArray<ImmutableArray<string>> PromotedStatePaths { get; init; }
    [JsonPropertyName("state")]
    public required PayloadType State { get; init; }
    [JsonPropertyName("until")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<Guard?> Until { get; init; }
}

[WireContract("GraphNode")]
public sealed record MapNode : GraphNode
{
    [JsonPropertyName("body")]
    public required GraphNode Body { get; init; }
    [JsonPropertyName("maxItems")]
    public required PositiveInteger MaxItems { get; init; }
    [JsonPropertyName("name")]
    public required NodeName Name { get; init; }
    [JsonPropertyName("over")]
    public required DataSelector Over { get; init; }
    [JsonPropertyName("promotedStatePaths")]
    public required ImmutableArray<ImmutableArray<string>> PromotedStatePaths { get; init; }
    [JsonPropertyName("state")]
    public required PayloadType State { get; init; }
}

[WireContract("GraphNode")]
public sealed record SucceedNode : GraphNode
{
    [JsonPropertyName("bindings")]
    public required ImmutableArray<InputBinding> Bindings { get; init; }
    [JsonPropertyName("name")]
    public required NodeName Name { get; init; }
    [JsonPropertyName("output")]
    public required PayloadType Output { get; init; }
}

[WireContract("GraphNode")]
public sealed record FailNode : GraphNode
{
    [JsonPropertyName("name")]
    public required NodeName Name { get; init; }
    [JsonPropertyName("reason")]
    public required FailReason Reason { get; init; }
}

[WireContract("GraphProfile")]
public enum GraphProfile
{
    [JsonStringEnumMemberName("openengine.graph.full/v1")]
    Full,
    [JsonStringEnumMemberName("openengine.graph.single-worker/v1")]
    SingleWorker,
}

[WireContract("GraphSpec")]
public sealed record GraphSpec : NativeContract
{
    [JsonPropertyName("initialInput")]
    public required PayloadType InitialInput { get; init; }
    [JsonPropertyName("policy")]
    public required PolicyBinding Policy { get; init; }
    [JsonPropertyName("profile")]
    public required GraphProfile Profile { get; init; }
    [JsonPropertyName("root")]
    public required GraphNode Root { get; init; }
}

[WireContract("Guard")]
[JsonPolymorphic(TypeDiscriminatorPropertyName = "kind")]
[JsonDerivedType(typeof(InGuard), "in")]
[JsonDerivedType(typeof(AllGuard), "all")]
[JsonDerivedType(typeof(AnyGuard), "any")]
[JsonDerivedType(typeof(NotGuard), "not")]
[JsonDerivedType(typeof(KOfNGuard), "k_of_n")]
[JsonDerivedType(typeof(KOfMapGuard), "k_of_map")]
public abstract record Guard : NativeContract
{
    private protected Guard() { }
}

[WireContract("Guard")]
public sealed record InGuard : Guard
{
    [JsonPropertyName("labels")]
    public required ImmutableArray<string> Labels { get; init; }
    [JsonPropertyName("value")]
    public required ControlSelector Value { get; init; }
}

[WireContract("Guard")]
public sealed record AllGuard : Guard
{
    [JsonPropertyName("guards")]
    public required ImmutableArray<Guard> Guards { get; init; }
}

[WireContract("Guard")]
public sealed record AnyGuard : Guard
{
    [JsonPropertyName("guards")]
    public required ImmutableArray<Guard> Guards { get; init; }
}

[WireContract("Guard")]
public sealed record NotGuard : Guard
{
    [JsonPropertyName("guard")]
    public required Guard Guard { get; init; }
}

[WireContract("Guard")]
public sealed record KOfNGuard : Guard
{
    [JsonPropertyName("count")]
    public required PositiveInteger Count { get; init; }
    [JsonPropertyName("labels")]
    public required ImmutableArray<string> Labels { get; init; }
    [JsonPropertyName("values")]
    public required ImmutableArray<ControlSelector> Values { get; init; }
}

[WireContract("Guard")]
public sealed record KOfMapGuard : Guard
{
    [JsonPropertyName("count")]
    public required PositiveInteger Count { get; init; }
    [JsonPropertyName("labels")]
    public required ImmutableArray<string> Labels { get; init; }
    [JsonPropertyName("value")]
    public required ControlSelector Value { get; init; }
}

[WireContract("InputBinding")]
public sealed record InputBinding : NativeContract
{
    [JsonPropertyName("target")]
    public required ImmutableArray<string> Target { get; init; }
    [JsonPropertyName("value")]
    public required DataSelector Value { get; init; }
}

[WireContract("Join")]
[JsonPolymorphic(TypeDiscriminatorPropertyName = "kind")]
[JsonDerivedType(typeof(AllJoin), "all")]
[JsonDerivedType(typeof(AnyJoin), "any")]
[JsonDerivedType(typeof(QuorumJoin), "quorum")]
[JsonDerivedType(typeof(FirstJoin), "first")]
public abstract record Join : NativeContract
{
    private protected Join() { }
}

[WireContract("Join")]
public sealed record AllJoin : Join
{
}

[WireContract("Join")]
public sealed record AnyJoin : Join
{
}

[WireContract("Join")]
public sealed record QuorumJoin : Join
{
    [JsonPropertyName("count")]
    public required PositiveInteger Count { get; init; }
}

[WireContract("Join")]
public sealed record FirstJoin : Join
{
    [JsonPropertyName("when")]
    public required Guard When { get; init; }
}

[WireContract("NodeOutputChannel")]
public enum NodeOutputChannel
{
    [JsonStringEnumMemberName("out")]
    Out,
    [JsonStringEnumMemberName("signal")]
    Signal,
    [JsonStringEnumMemberName("diagnostic")]
    Diagnostic,
}

[WireContract("NodeOutputSelector")]
public sealed record NodeOutputSelector : NativeContract
{
    [JsonPropertyName("channel")]
    public required NodeOutputChannel Channel { get; init; }
    [JsonPropertyName("node")]
    public required NodeName Node { get; init; }
    [JsonPropertyName("path")]
    public required ImmutableArray<string> Path { get; init; }
}

[WireContract("NodeRuntimeBinding")]
[JsonPolymorphic(TypeDiscriminatorPropertyName = "kind")]
[JsonDerivedType(typeof(AgentBinding), "agent")]
[JsonDerivedType(typeof(GitDeliveryBinding), "git_delivery")]
public abstract record NodeRuntimeBinding : NativeContract
{
    private protected NodeRuntimeBinding() { }
}

[WireContract("NodeRuntimeBinding")]
public sealed record AgentBinding : NodeRuntimeBinding
{
    [JsonPropertyName("connections")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<ImmutableDictionary<string, ImmutableArray<string>>> Connections { get; init; }
    [JsonPropertyName("effort")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<ReasoningEffort?> Effort { get; init; }
    [JsonPropertyName("model")]
    public required ModelId Model { get; init; }
    [JsonPropertyName("sessionScope")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<SessionScope> SessionScope { get; init; }
}

[WireContract("NodeRuntimeBinding")]
public sealed record GitDeliveryBinding : NodeRuntimeBinding
{
    [JsonPropertyName("connections")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<ImmutableDictionary<string, ImmutableArray<string>>> Connections { get; init; }
    [JsonPropertyName("pullRequestFeedback")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<PullRequestFeedback> PullRequestFeedback { get; init; }
}

[WireContract("PayloadType")]
[JsonPolymorphic(TypeDiscriminatorPropertyName = "kind")]
[JsonDerivedType(typeof(NullPayload), "null")]
[JsonDerivedType(typeof(BooleanPayload), "boolean")]
[JsonDerivedType(typeof(IntegerPayload), "integer")]
[JsonDerivedType(typeof(NumberPayload), "number")]
[JsonDerivedType(typeof(StringPayload), "string")]
[JsonDerivedType(typeof(RecordPayload), "record")]
[JsonDerivedType(typeof(ArrayPayload), "array")]
[JsonDerivedType(typeof(EnumPayload), "enum")]
public abstract record PayloadType : NativeContract
{
    private protected PayloadType() { }
}

[WireContract("PayloadType")]
public sealed record NullPayload : PayloadType
{
}

[WireContract("PayloadType")]
public sealed record BooleanPayload : PayloadType
{
}

[WireContract("PayloadType")]
public sealed record IntegerPayload : PayloadType
{
}

[WireContract("PayloadType")]
public sealed record NumberPayload : PayloadType
{
}

[WireContract("PayloadType")]
public sealed record StringPayload : PayloadType
{
}

[WireContract("PayloadType")]
public sealed record RecordPayload : PayloadType
{
    [JsonPropertyName("fields")]
    public required ImmutableDictionary<string, RecordField> Fields { get; init; }
}

[WireContract("PayloadType")]
public sealed record ArrayPayload : PayloadType
{
    [JsonPropertyName("items")]
    public required PayloadType Items { get; init; }
}

[WireContract("PayloadType")]
public sealed record EnumPayload : PayloadType
{
    [JsonPropertyName("values")]
    public required ImmutableArray<string> Values { get; init; }
}

[WireContract("PolicyBinding")]
public sealed record PolicyBinding : NativeContract
{
    [JsonPropertyName("default")]
    public required PolicyDefault Default { get; init; }
    [JsonPropertyName("policy")]
    public required PolicyRef Policy { get; init; }
}

[WireContract("PolicyDefault")]
public enum PolicyDefault
{
    [JsonStringEnumMemberName("deny")]
    Deny,
}

[WireContract("PullRequestFeedback")]
public enum PullRequestFeedback
{
    [JsonStringEnumMemberName("consider")]
    Consider,
    [JsonStringEnumMemberName("ignore")]
    Ignore,
}

[WireContract("ReasoningEffort")]
public enum ReasoningEffort
{
    [JsonStringEnumMemberName("low")]
    Low,
    [JsonStringEnumMemberName("medium")]
    Medium,
    [JsonStringEnumMemberName("high")]
    High,
    [JsonStringEnumMemberName("xhigh")]
    XHigh,
    [JsonStringEnumMemberName("max")]
    Max,
}

[WireContract("RecordField")]
public sealed record RecordField : NativeContract
{
    [JsonPropertyName("required")]
    public required bool Required { get; init; }
    [JsonPropertyName("type")]
    public required PayloadType Type { get; init; }
}

[WireContract("RedactionClass")]
public enum RedactionClass
{
    [JsonStringEnumMemberName("public")]
    Public,
    [JsonStringEnumMemberName("internal")]
    Internal,
    [JsonStringEnumMemberName("confidential")]
    Confidential,
    [JsonStringEnumMemberName("restricted")]
    Restricted,
}

[WireContract("ResolvedSource")]
public sealed record ResolvedSource : NativeContract
{
    [JsonPropertyName("branch")]
    public required SourceBranchId Branch { get; init; }
    [JsonPropertyName("repository")]
    public required SourceRepositoryId Repository { get; init; }
    [JsonPropertyName("revision")]
    public required SourceRevisionId Revision { get; init; }
}

[WireContract("RunSize")]
public enum RunSize
{
    [JsonStringEnumMemberName("small")]
    Small,
    [JsonStringEnumMemberName("medium")]
    Medium,
    [JsonStringEnumMemberName("large")]
    Large,
}

[WireContract("RunSubmission")]
public sealed record RunSubmission : NativeContract
{
    [JsonPropertyName("environment")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<RuntimeEnvironment?> Environment { get; init; }
    [JsonPropertyName("graph")]
    public required GraphSpec Graph { get; init; }
    [JsonPropertyName("initialInput")]
    public required JsonElement InitialInput { get; init; }
    [JsonPropertyName("runtime")]
    public required RuntimePlan Runtime { get; init; }
    [JsonPropertyName("source")]
    public required ResolvedSource Source { get; init; }
    [JsonPropertyName("submissionKey")]
    public required IdempotencyKey SubmissionKey { get; init; }
    [JsonPropertyName("title")]
    public required RunTitle Title { get; init; }
}

[WireContract("RunSubmitParams")]
public sealed record RunSubmitParams : NativeContract
{
    [JsonPropertyName("runId")]
    public required RunId RunId { get; init; }
    [JsonPropertyName("submission")]
    public required RunSubmission Submission { get; init; }
}

[WireContract("RuntimeEnvironment")]
public sealed record RuntimeEnvironment : NativeContract
{
    [JsonPropertyName("connections")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<ImmutableDictionary<string, ImmutableArray<string>>> Connections { get; init; }
    [JsonPropertyName("setup")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> Setup { get; init; }
    [JsonPropertyName("startup")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> Startup { get; init; }
    [JsonPropertyName("variables")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<ImmutableDictionary<string, string>> Variables { get; init; }
}

[WireContract("RuntimePlan")]
[JsonPolymorphic(TypeDiscriminatorPropertyName = "harness")]
[JsonDerivedType(typeof(CopilotRuntime), "copilot")]
[JsonDerivedType(typeof(CodexRuntime), "codex")]
[JsonDerivedType(typeof(ClaudeRuntime), "claude")]
public abstract record RuntimePlan : NativeContract
{
    private protected RuntimePlan() { }
}

[WireContract("RuntimePlan")]
public sealed record CopilotRuntime : RuntimePlan
{
    [JsonPropertyName("nodes")]
    public required ImmutableDictionary<string, NodeRuntimeBinding> Nodes { get; init; }
    [JsonPropertyName("provider")]
    public required CopilotProvider Provider { get; init; }
    [JsonPropertyName("size")]
    public required RunSize Size { get; init; }
}

[WireContract("RuntimePlan")]
public sealed record CodexRuntime : RuntimePlan
{
    [JsonPropertyName("nodes")]
    public required ImmutableDictionary<string, NodeRuntimeBinding> Nodes { get; init; }
    [JsonPropertyName("provider")]
    public required CodexProvider Provider { get; init; }
    [JsonPropertyName("size")]
    public required RunSize Size { get; init; }
}

[WireContract("RuntimePlan")]
public sealed record ClaudeRuntime : RuntimePlan
{
    [JsonPropertyName("nodes")]
    public required ImmutableDictionary<string, NodeRuntimeBinding> Nodes { get; init; }
    [JsonPropertyName("provider")]
    public required ClaudeProvider Provider { get; init; }
    [JsonPropertyName("size")]
    public required RunSize Size { get; init; }
}

[WireContract("SessionScope")]
public enum SessionScope
{
    [JsonStringEnumMemberName("execution")]
    Execution,
    [JsonStringEnumMemberName("node_instance")]
    NodeInstance,
}

[WireContract("StructuralBounds")]
public sealed record StructuralBounds : NativeContract
{
    [JsonPropertyName("attemptsPerNode")]
    public required ImmutableDictionary<string, PositiveInteger> AttemptsPerNode { get; init; }
    [JsonPropertyName("maxNodeExecutions")]
    public required PositiveInteger MaxNodeExecutions { get; init; }
    [JsonPropertyName("peakConcurrency")]
    public required PositiveInteger PeakConcurrency { get; init; }
    [JsonPropertyName("termination")]
    public required TerminationWitness Termination { get; init; }
}

[WireContract("TerminationWitness")]
[JsonPolymorphic(TypeDiscriminatorPropertyName = "kind")]
[JsonDerivedType(typeof(AcyclicWitness), "acyclic")]
[JsonDerivedType(typeof(BoundedWitness), "bounded")]
public abstract record TerminationWitness : NativeContract
{
    private protected TerminationWitness() { }
}

[WireContract("TerminationWitness")]
public sealed record AcyclicWitness : TerminationWitness
{
    [JsonPropertyName("order")]
    public required ImmutableArray<string> Order { get; init; }
}

[WireContract("TerminationWitness")]
public sealed record BoundedWitness : TerminationWitness
{
    [JsonPropertyName("maxIterations")]
    public required PositiveInteger MaxIterations { get; init; }
    [JsonPropertyName("ranking")]
    public required ImmutableArray<ImmutableArray<string>> Ranking { get; init; }
}

[WireContract("VerifierContract")]
public sealed record VerifierContract : NativeContract
{
    [JsonPropertyName("diagnostic")]
    public required PayloadType Diagnostic { get; init; }
    [JsonPropertyName("signals")]
    public required ImmutableDictionary<string, ImmutableArray<string>> Signals { get; init; }
}

[WireContract("WorkerContract")]
public sealed record WorkerContract : NativeContract
{
    [JsonPropertyName("errors")]
    public required ImmutableArray<WorkerErrorCode> Errors { get; init; }
    [JsonPropertyName("input")]
    public required PayloadType Input { get; init; }
    [JsonPropertyName("output")]
    public required PayloadType Output { get; init; }
    [JsonPropertyName("verifier")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<VerifierContract?> Verifier { get; init; }
}

[WireContract("WorkerDescriptor")]
public sealed record WorkerDescriptor : NativeContract
{
    [JsonPropertyName("artifactProfile")]
    public required ArtifactResultProfile ArtifactProfile { get; init; }
    [JsonPropertyName("binding")]
    public required WorkerProtocolBinding Binding { get; init; }
    [JsonPropertyName("capabilityPolicy")]
    public required CapabilityPolicy CapabilityPolicy { get; init; }
    [JsonPropertyName("contract")]
    public required WorkerContract Contract { get; init; }
    [JsonPropertyName("credentialRequirements")]
    public required ImmutableArray<CredentialHandle> CredentialRequirements { get; init; }
    [JsonPropertyName("graphProfiles")]
    public required ImmutableArray<GraphProfile> GraphProfiles { get; init; }
    [JsonPropertyName("worker")]
    public required WorkerRef Worker { get; init; }
}

[WireContract("WorkerErrorCode")]
public enum WorkerErrorCode
{
    [JsonStringEnumMemberName("timeout")]
    Timeout,
    [JsonStringEnumMemberName("crash")]
    Crash,
    [JsonStringEnumMemberName("malformed")]
    Malformed,
    [JsonStringEnumMemberName("refusal")]
    Refusal,
}

[WireContract("WorkerFailureReason")]
public enum WorkerFailureReason
{
    [JsonStringEnumMemberName("declared_failure")]
    DeclaredFailure,
    [JsonStringEnumMemberName("policy_denied")]
    PolicyDenied,
    [JsonStringEnumMemberName("interactive_input_required")]
    InteractiveInputRequired,
    [JsonStringEnumMemberName("authentication_required")]
    AuthenticationRequired,
    [JsonStringEnumMemberName("malformed_result")]
    MalformedResult,
}

[WireContract("WorkerOutcome")]
[JsonPolymorphic(TypeDiscriminatorPropertyName = "status")]
[JsonDerivedType(typeof(VerifiedOutcome), "verified")]
[JsonDerivedType(typeof(VerifierOutcome), "verifier")]
[JsonDerivedType(typeof(ErrorOutcome), "error")]
public abstract record WorkerOutcome : NativeContract
{
    private protected WorkerOutcome() { }
}

[WireContract("WorkerOutcome")]
public sealed record VerifiedOutcome : WorkerOutcome
{
    [JsonPropertyName("artifacts")]
    public required ImmutableArray<ArtifactRef> Artifacts { get; init; }
    [JsonPropertyName("output")]
    public required JsonElement Output { get; init; }
}

[WireContract("WorkerOutcome")]
public sealed record VerifierOutcome : WorkerOutcome
{
    [JsonPropertyName("artifacts")]
    public required ImmutableArray<ArtifactRef> Artifacts { get; init; }
    [JsonPropertyName("diagnostic")]
    public required JsonElement Diagnostic { get; init; }
    [JsonPropertyName("output")]
    public required JsonElement Output { get; init; }
    [JsonPropertyName("signals")]
    public required ImmutableDictionary<string, string> Signals { get; init; }
}

[WireContract("WorkerOutcome")]
public sealed record ErrorOutcome : WorkerOutcome
{
    [JsonPropertyName("code")]
    public required WorkerErrorCode Code { get; init; }
    [JsonPropertyName("reason")]
    public required WorkerFailureReason Reason { get; init; }
}

[WireContract("WorkerProtocolBinding")]
public sealed record WorkerProtocolBinding : NativeContract
{
    [JsonPropertyName("profile")]
    public required string Profile { get; init; }
    [JsonPropertyName("protocol")]
    public required string Protocol { get; init; }
    [JsonPropertyName("version")]
    public required string Version { get; init; }
}

[WireContract("WriteBinding")]
public sealed record WriteBinding : NativeContract
{
    [JsonPropertyName("target")]
    public required ImmutableArray<string> Target { get; init; }
    [JsonPropertyName("value")]
    public required NodeOutputSelector Value { get; init; }
}
