#!/usr/bin/env python3
"""Regenerate C# wire DTOs from the checked-in pinned contract closure (development only)."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
defs = json.loads((root / 'src/Zeroshot.Sdk/Schemas/contracts.schema.json').read_text())['$defs']
lines = ['// Generated by tools/generate-contracts.py from the pinned native schemas.',
         '#nullable enable', 'using System.Collections.Immutable;', 'using System.Text.Json;',
         'using System.Text.Json.Serialization;', '', 'namespace Zeroshot.Native.Contracts;', '']
aliases = {'WorkerDescriptorWire': 'WorkerDescriptor', 'WorkerOutcomeWire': 'WorkerOutcome'}
scalar_refs = {'CredentialHandle', 'NodeInstructions'}
primitive_fields = {
 'name': 'NodeName', 'worker': 'WorkerRef', 'policy': 'PolicyRef', 'permissionPolicy': 'PolicyRef',
 'runId': 'RunId', 'submissionKey': 'IdempotencyKey', 'title': 'RunTitle', 'model': 'ModelId',
 'repository': 'SourceRepositoryId', 'branch': 'SourceBranchId', 'revision': 'SourceRevisionId',
 'artifactId': 'ArtifactId', 'sha256': 'Sha256Digest', 'mediaType': 'MediaType', 'typeId': 'TypeId',
 'node': 'NodeName', 'field': 'FieldName'}
def pascal(s):
 return ''.join(p[:1].upper()+p[1:] for p in s.replace('-','_').replace('/','_').split('_'))
def typ(s, field=''):
 if s is True or s == {}: return 'JsonElement'
 if s.get('enum')==['timeout','crash','malformed','refusal']:return 'WorkerErrorCode'
 if '$ref' in s:
  name = s['$ref'].split('/')[-1]
  if name.startswith('NonEmptyVec_of_') or name in ('DeclaredConnections','DeclaredEnvironment'):
   return typ(defs[name])
  return aliases.get(name, name)
 if 'anyOf' in s:
  real=[x for x in s['anyOf'] if x.get('type')!='null']
  if len(real)==1: return typ(real[0],field)+'?'
 t=s.get('type')
 if isinstance(t,list):
  q=dict(s);q['type']=next(x for x in t if x!='null')
  return typ(q,field)+'?'
 if t=='string':return primitive_fields.get(field,'string')
 if t=='integer' and s.get('format')=='uint32':return 'uint'
 if t=='integer':return 'PositiveInteger' if s.get('minimum')==1 and s.get('maximum')==9007199254740991 else 'ByteLength' if field=='byteLength' else 'Generation' if field=='generation' else 'ulong'
 if t=='boolean':return 'bool'
 if t=='array':return 'ImmutableArray<'+typ(s['items'])+'>'
 if t=='object' and 'properties' not in s:
  item=s.get('additionalProperties')
  if not isinstance(item,dict):item=next(iter(s.get('patternProperties',{}).values()),True)
  return 'ImmutableDictionary<string, '+typ(item)+'>'
 raise ValueError(s)
def model(name,s,base='NativeContract',schema_name=None,tag=None):
 schema_name=schema_name or name
 lines.extend(['[WireContract("'+schema_name+'")]', 'public sealed record '+name+' : '+base,'{'])
 for key,value in s.get('properties',{}).items():
  if key==tag:continue
  t=typ(value,key);optional=key not in s.get('required',[])
  if name=='FieldDiagnosticPathSegment' and key=='name': t='FieldName'
  elif name=='FailNode' and key=='reason': t='FailReason'
  elif optional:t='Optional<'+t+'>'
  lines.append('    [JsonPropertyName("'+key+'")]')
  if optional:lines.append('    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]')
  lines.append('    public '+('' if optional else 'required ')+t+' '+pascal(key)+' { get; init; }')
 lines.extend(['}', ''])
for name,s in defs.items():
 if name in aliases or name in scalar_refs or name.startswith('NonEmptyVec_of_') or name in ('DeclaredConnections','DeclaredEnvironment'):continue
 if name=='WorkerDescriptor':model(name,defs['WorkerDescriptorWire']);continue
 if name=='WorkerOutcome':s=defs['WorkerOutcomeWire']
 if 'enum' in s:
  if name=='RunSize': values=['small','medium','large']
  else:values=s['enum']
  lines.extend(['[WireContract("'+name+'")]', 'public enum '+name,'{'])
  for value in values:
   member={'openengine.graph.full/v1':'Full','openengine.graph.single-worker/v1':'SingleWorker','openai':'OpenAi','openrouter':'OpenRouter','xhigh':'XHigh'}.get(value,pascal(value))
   lines.extend(['    [JsonStringEnumMemberName("'+value+'")]', '    '+member+','])
  lines.extend(['}', '']);continue
 if 'oneOf' in s:
  variants=s['oneOf']; tag=next(k for k,v in variants[0]['properties'].items() if isinstance(v,dict) and 'const' in v)
  vnames=[]
  for v in variants:
   label=v['properties'][tag]['const']
   suffix={'GraphNode':'Node','PayloadType':'Payload','Guard':'Guard','Join':'Join','DataSelector':'Selector','RuntimePlan':'Runtime','NodeRuntimeBinding':'Binding','WorkerOutcome':'Outcome','TerminationWitness':'Witness'}.get(name,name)
   vnames.append((pascal(label)+suffix,label,v))
  lines.extend(['[WireContract("'+name+'")]', '[JsonPolymorphic(TypeDiscriminatorPropertyName = "'+tag+'")]'])
  for vn,label,v in vnames:lines.append('[JsonDerivedType(typeof('+vn+'), "'+label+'")]')
  lines.extend(['public abstract record '+name+' : NativeContract', '{', '    private protected '+name+'() { }', '}', ''])
  for vn,label,v in vnames:model(vn,v,name,name,tag)
 elif s.get('type')=='object':model(name,s)
 else:raise ValueError((name,s))
(root/'src/Zeroshot.Sdk/Contracts/Models.g.cs').write_text('\n'.join(lines))
